server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/deeplearning?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: xieyc@mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat,wall,config,log4j
      use-global-data-source-stat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      max-active: 100
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20

# ============ 认证信息 =========
pay:
  auth:
    wx:
      app-id: wxd898fcb01713c658
      mch-id: 1483469312
      mch-key: 098F6BCD4621D373CADE4E832627B4F6
      notify-url: http://wyx9y6.natappfree.cc/wxPay/notify
      return-url: http://127.0.0.1:5000/imall/Order
    ali:
      app-id: 2018062960540016
      notify-url: http://wyx9y6.natappfree.cc/aliPay/notify
      return-url: http://127.0.0.1:5000/imall/Order
#============= 密钥信息 ==========
  encode:
    secretKey: deepLearning-dev@secretKey
    aesKey: deepLearning-dev@aesKey
#============== 支付回调地址 =======
  outsideurl:
    syncCallPayUrl: http://127.0.0.1:8082/mallOrder/syncCallBackPay
